/**
 * Regenerates the static social/app images in `public/`.
 * Run with `npm run images` after changing the wording or the brand colours.
 *
 * They are committed rather than built on every deploy: they change once a
 * year at most, and keeping them static keeps the CI step trivial.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = resolve(root, 'public');

const GROUND = '#070708';
const INK = '#f4f4f3';
const MUTED = '#83838c';
const ACCENT = '#7fe3d0';

const ogSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <rect width="1200" height="630" fill="${GROUND}"/>
  <rect x="24" y="24" width="1152" height="582" rx="40" fill="#0e0e10" stroke="rgba(255,255,255,0.09)"/>
  <circle cx="1105" cy="120" r="230" fill="none" stroke="rgba(255,255,255,0.06)"/>
  <circle cx="120" cy="600" r="170" fill="none" stroke="rgba(255,255,255,0.06)"/>

  <text x="80" y="118" font-family="Consolas,'DejaVu Sans Mono',monospace" font-size="26" fill="${MUTED}">
    arix-alimagnidokpo.github.io
  </text>

  <text x="76" y="300" font-family="Consolas,'DejaVu Sans Mono',monospace" font-size="112" font-weight="800" letter-spacing="-6" fill="${INK}">
    AI &amp; NLP
  </text>
  <text x="76" y="410" font-family="Consolas,'DejaVu Sans Mono',monospace" font-size="112" font-weight="800" letter-spacing="-6" fill="${INK}">
    Engineer
  </text>

  <rect x="76" y="452" width="360" height="3" fill="${ACCENT}"/>

  <text x="76" y="520" font-family="'Inter','DejaVu Sans',sans-serif" font-size="34" font-weight="600" fill="${INK}">
    Arix ALIMAGNIDOKPO
  </text>
  <text x="76" y="562" font-family="'Inter','DejaVu Sans',sans-serif" font-size="26" fill="${MUTED}">
    Founder &amp; CEO, AIDA — Cotonou, Benin
  </text>
</svg>`;

const iconSvg = `<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="14" fill="${GROUND}"/>
  <path d="M16 47 32 17l16 30" fill="none" stroke="${INK}" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M23.5 38h17" fill="none" stroke="${ACCENT}" stroke-width="5" stroke-linecap="round"/>
</svg>`;

await mkdir(publicDir, { recursive: true });

await sharp(Buffer.from(ogSvg)).png({ compressionLevel: 9 }).toFile(resolve(publicDir, 'og.png'));
await sharp(Buffer.from(iconSvg)).png({ compressionLevel: 9 }).toFile(resolve(publicDir, 'apple-touch-icon.png'));

await writeFile(
  resolve(publicDir, '.images-generated'),
  `Generated by scripts/generate-images.mjs on ${new Date().toISOString().slice(0, 10)}\n`,
  'utf8',
);

console.log('Wrote public/og.png and public/apple-touch-icon.png');
